config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => {
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root to: 'home#index'
  get '/', to: 'home#index'
  #get '/users/sign_in', to: 'home#index'
  #get '/users/sign_up', to: 'home#index'
  get '/terms', to: 'home#index'
  resources :users, only: [:show, :edit, :update]
  get '/dashboard', to: 'dashboard#index'
  get '/explore', to: 'explore#index'
  get '/settings', to: 'settings#edit', as: :edit_settings
  post '/settings/update', to: 'settings#update', as: :update_settings
  post '/stripe/disconnect', to: 'stripe#disconnect', as: :disconnect_stripe_account
  resources :charges, only: [:new, :create]
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!

  require "stripe"
  require "net/http"
  require "uri"
  require "json"
  Stripe.api_key = ENV["STRIPE_SECRET_KEY"]

  def edit
    @user = current_user
    @oauth_link = ENV["STRIPE_OAUTH_LINK"]

    if params[:code] && @user.stripe_id==nil
      # Callback
      authorization_code = params[:code]

      # Fetch the user's credentials from Stripe
      uri = URI.parse("https://connect.stripe.com/oauth/token")
      request = Net::HTTP::Post.new(uri)
      request.set_form_data(
        "client_secret" => Stripe.api_key,
        "code" => authorization_code,
        "grant_type" => "authorization_code",
      )

      req_options = {
        use_ssl: uri.scheme == "https",
      }

      response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
        http.request(request)
      end

      if response.code == "200"
        res = JSON.parse(response.body)
        @user.update!(stripe_id: res["stripe_user_id"]) if res
      else
        flash[:alert] = "Bad request."
      end
    end
    @acct = Stripe::Account.retrieve(@user.stripe_id) if @user.stripe_id
  end

  def update
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/edit.html.erb
<main class="container">
  <div class="row justify-content-center my-4">
    <h1>Dashboard</h1>
    <div class="w-100"></div>
    <div class="col-lg">
      <ul class="nav nav-tabs nav-fill">
        <li class="nav-item">
          <a class="nav-link" href="/dashboard">概要</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= edit_user_path(current_user) %>">ユーザー編集</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-info active" href="/settings">各種設定</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="col-xl">
    <div class="w-100"></div>
    <% if alert != nil %>
      <div class="alert alert-warning alert-dismissible fade show mt-2 mb-0" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <div class="card shadow ml-3 my-5"> 
      <div class="card-body">
        <h5 class="ml-1">支払い方法</h5>
        <% if @user.stripe_id %>
          <%= image_tag "stripe-logo-blue.png", :size => "100x50" %>
          <div class="d-inline-flex h4"> 
            <span class="badge badge-pill badge-success h6">接続済</span>
            <div class="btn-group ml-2">
              <button type="button" class="btn btn-sm btn-dark"><%= @acct["email"] %></button>
              <button type="button" class="btn btn-dark dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <div class="dropdown-menu">
                <a href="https://dashboard.stripe.com/dashboard" class="dropdown-item">
                  Stripe Dashboard
                </a>
                <%= link_to "接続解除", disconnect_stripe_account_path, method: :post, class: "dropdown-item" %>
              </div>
            </div>
          </div>
        <% else %>
          <a href="<%= @oauth_link %>" data-toggle="tooltip" data-placement="right" title="
          Stripeはオンライン決済のプラットフォームです。アカウント登録されていない方はこちらから登録してください。
          ">
          <%= image_tag "light-on-light.png", class: "my-3" %>
          </a>
        <% end %>
        <br />
        <br />
        <br />
        <br />
        <br />
      </div>
    </div>
  </div>
  <% 20.times do |br| %>
    <br />
  <% end %>
</main>

app/views/settings/update.html.erb
<h1>Settings#update</h1>
<p>Find me in app/views/settings/update.html.erb</p>