config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => {
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root to: 'home#index'
  get '/', to: 'home#index'
  #get '/users/sign_in', to: 'home#index'
  #get '/users/sign_up', to: 'home#index'
  get '/terms', to: 'home#index'
  resources :users, only: [:show, :edit, :update]
  get '/dashboard', to: 'dashboard#index'
  get '/explore', to: 'explore#index'
  get '/settings', to: 'settings#edit', as: :edit_settings
  post '/settings/update', to: 'settings#update', as: :update_settings
  post '/stripe/disconnect', to: 'stripe#disconnect', as: :disconnect_stripe_account
  resources :charges, only: [:new, :create]
end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController
  def index
    @searched = User.search(params[:keyword]).reverse_order.page(params[:page])
  end
end

app/helpers/explore_helper.rb
module ExploreHelper
end

app/views/explore/index.html.erb
<main class="container">
  <div class="row justify-content-center my-4">
  <h4>クリエイターを探す</h4>
  <div class="w-100"></div>
    <!-- Search fomr -->
    <%= form_with url: explore_path, method: :get, local: true, class: "form-inline my-lg-4" do |f| %>
      <%= f.text_field :keyword, class: "form-control mr-2", placeholder: "Search" %>
      <%= f.submit("検索", class: "btn btn-outline-dark my-2 my-sm-0 ml-2") %>
    <% end %>
    <div class="w-100"></div>
    <% @searched.each do |user| %>
      <div class="card col-md-3 mx-3 my-2 shadow-sm" style="width: 20rem;">
        <div class="row no-gutters mt-2">
          <div class="col-md-4 ml-2">
            <div class="user-image my-3">
              <%= attachment_image_tag user, :image, :fill, 100, 100, :size => "60x60",  fallback: "no-user-image.jpg" %>
            </div>
          </div>
          <div class="card-body col-md-5 ml-2">
            <h6 class="card-title"><%= user.name %></h6>
            <h6 class="card-subtitle mb-2 text-muted">
              <% if user.occupation %>
                <%= user.occupation %>
              <% else %>
                <span>Artist</span>
              <% end %>
            </h6>
          </div>
          <div class="w-100"></div>
          <div class="card-text ml-2">
            <% if user.introduction %>
              <% if user.introduction.length > 50 %>
                <p><%= user.introduction[0,50] %> ...</p>
              <% else %>
                <p><%= user.introduction %></p>
              <% end %>
            <% else %>
              <br />
              <br />
              <br />
            <% end %>
          </div>
          <a href="<%= user_path(user.id) %>" class="stretched-link"></a>
        </div>
      </div>
    <% end %>
    <% if @searched.count == 0 %>
      <p><strong><%= params[:keyword] %></strong> に一致するユーザーは見つかりませんでした。</p>
    <% end %>
  </div>
  <div class="row justify-content-center mb-5">
    <%= paginate @searched, class: "pagenate" %>
  </div>
  <br>
  <br>
</main>